<a href="https://colab.research.google.com/github/PythDani/ManipulacionDeDatos/blob/master/condiciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr=np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
ind_cond= arr>5
ind_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [7]:
arr[ind_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [10]:
arr[(arr>5)]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [11]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)