<a href="https://colab.research.google.com/github/PythDani/ManipulacionDeDatos/blob/master/creandoArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr= np.array(list(range(0,10)))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2) #de dos en dos del 0 al 20

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(2) #Definir arrays en ceros, se usa para crear una estructura en cero

array([0., 0.])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((10,10,10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,100)
# linspace(0,10,100) es una función de la biblioteca NumPy de Python 
# que crea una secuencia de números igualmente espaciados en el intervalo [0, 10].
# En particular, los tres argumentos de esta función son los siguientes:
# 0 representa el valor inicial del intervalo.
# 10 representa el valor final del intervalo.
# 100 representa el número de elementos que se quieren generar en la secuencia.
# Por lo tanto, np.linspace(0, 10, 100) generará una secuencia de 100 números que van desde 0 hasta 10,
# ambos inclusive, y donde cada número estará separado por una distancia igual.
# Esta función es muy útil para generar una cuadrícula de puntos a lo largo de un intervalo en una dimensión específica,
# lo que es útil en muchas aplicaciones, como la graficación de funciones y la solución de ecuaciones diferenciales.

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(4) #matriz con diagonal principal en 1 nxn donde n es el argumento en np.eye(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand() #aleatorio entre 0 y 1

0.7013159782023841

In [ ]:
arr=np.random.rand(4) 
print(arr, "  Dimensiones: " , arr.ndim)

[0.94418415 0.04828519 0.34341053 0.48186117]   Dimensiones:  1


In [ ]:
np.random.rand(4,4)

array([[0.55510081, 0.93877847, 0.90893206, 0.75337922],
       [0.4064425 , 0.65189609, 0.01903605, 0.5450183 ],
       [0.12598358, 0.93090555, 0.74384382, 0.25841322],
       [0.72564381, 0.55188502, 0.20183381, 0.6151064 ]])

In [ ]:
np.random.randint(1,15)

5

In [ ]:
np.random.randint(1,100, (10,10))

array([[51, 75,  7, 93, 54,  5, 15, 91, 53, 60],
       [98, 46, 82, 33, 50, 78,  3, 24, 48, 39],
       [59, 24, 59, 87, 49, 53, 41, 58, 39, 14],
       [84, 37, 31, 32,  1, 23, 31, 96, 65,  7],
       [77, 19, 74, 75, 96, 95, 50, 94, 44, 32],
       [48, 24, 17, 17, 20, 60, 58, 10, 13, 62],
       [52, 24, 78, 42, 37, 44, 23, 80, 35, 81],
       [67, 31, 21, 73, 11, 30, 75, 55, 40, 19],
       [58, 29, 96, 27, 95, 10, 52, 11, 57, 47],
       [49, 59, 50, 43, 92, 23, 94, 68, 40,  3]])

In [ ]:
arrZ= np.array(1)
print(arrZ, "Dimensiones: ", arrZ.ndim)

1 Dimensiones:  0
