<a href="https://colab.research.google.com/github/PythDani/cursoManipulacionDeDatos/blob/master/elArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
lista=[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)
print(type(arr))
arr


<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0] +arr[5]


7

In [ ]:
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(matriz[0])
print(matriz[1])
print(matriz[2])
print(matriz[0,2])
print(matriz[0,1])
print(matriz[1,2])

[1 2 3]
[4 5 6]
[7 8 9]
3
2
6


In [ ]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:3]
arr[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
print(arr[0:])
print(arr[2:])
print(arr[1:])
print(arr[:])
print(arr[::3])
print(arr[-3:])
print(arr[-5:-2])

[1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7]
[7 8 9]
[5 6 7]


In [ ]:
print(matriz)
print("--------------")
print(matriz[1:])
print(matriz[1:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


In [ ]:
matriz2 = [[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]]
matriz2

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [ ]:
matriz3= np.array(matriz2)
matriz3





      

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
print(matriz3[0])
print(matriz3[1])
print(matriz3[0,2])
print(matriz3[1,2])
print(matriz3[0,2,1])
print(matriz3[0,1,1])
print(matriz3[1,0,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[ 9 10 11 12]
[21 22 23 24]
10
6
15


In [ ]:
print(matriz3
      )

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
#print(matriz3[0:])
#print(matriz3[1:])
print(matriz3[1:, 0:2, 1:3])

[[[14 15]
  [18 19]]]
