<a href="https://colab.research.google.com/github/PythDani/ManipulacionDeDatos/blob/master/funciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.random.randint(2,6, 10) 
#np.random.randint(x,y,n) genera un array de n elementos 
#Los elementos del array se crean de forma aleatoria debido a randon.randint método
# En el rando desde x inclusive hasta y. 

array([4, 4, 4, 5, 2, 5, 4, 3, 4, 4])

In [ ]:
arr = np.random.randint(2,6, 10) 
arr 
#Imprimirá un vector

array([5, 5, 4, 5, 4, 3, 3, 4, 4, 4])

In [ ]:
matriz=arr.reshape(2,5)
matriz 
#imprimirá una estructura matricial

array([[5, 5, 4, 5, 4],
       [3, 3, 4, 4, 4]])

In [ ]:
arr.max()
#max() nos retorna el número más grande del vector o matriz
matriz.max()

5

In [ ]:
matriz.max()

5

In [ ]:
matriz.max(1)
#El argumento n en matriz.max(n) representa el eje por el cual queremos obtener el o los valores máximos
# siendo n=0 el eje de las columnas y n=1 el eje de las filas. Ver ejemplo con cero más abajo.
#El método compara por cada fila o culumna, de a cuerdo al valor n dado, y obtiene el máximo valor


array([5, 4])

In [ ]:
matriz.max(0)

array([2, 5, 5, 5, 4])

In [ ]:
arr.argmax()
#Nos devuelve el indice donde se encuentra el valor más alto.

0

In [ ]:
matriz.argmax(0)

array([0, 0, 0, 0, 0])

In [ ]:
arr.min()

3

In [ ]:
matriz.min()

3

In [ ]:
arr.argmin()

5

In [ ]:
#arr.ptp()  de un pico al otro pico: del pico mas bajo al mas alto. y la diferencia es lo que nos retorna
#np.percentile(array, 50) especifica el percentil que estoy trabajando, en este caso el valor que se encuentra en la mitad percentiles: 0, 100 y 50
#arr.sort() Ordena de menor a mayor los numeros del arreglo
#np.median(arr) igual que percentile. En este caso que es un vector
#np.median(matriz, 1)
#np.std(arr) desviacion estándar
#np.var(arr) varianza == np.std(arr) **2
#np.mean(arr) promedio
#-------------------------------------------------------------------------------------------------------------------

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([4,6])


In [ ]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])

In [ ]:
a.ndim
b.ndim

1

In [ ]:
b = np.expand_dims(b, axis=0)
b
b.ndim

2

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])