<a href="https://colab.research.google.com/github/PythDani/ManipulacionDeDatos/blob/master/tiposDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arrayA =[1,2,3,4]
arrayA = np.array(arrayA)
arrayA
arrayA.dtype

dtype('int64')

In [ ]:
arr = np.array([ 1,2,3,4,5], dtype="float64")
arr.dtype
print(arr.dtype)
arrayA

float64


array([1, 2, 3, 4])

In [ ]:
arrayA = arrayA.astype(np.float64)
arrayA
arr = arr.astype(np.bool_)
arr

array([ True,  True,  True,  True,  True])

In [ ]:
import numpy as np
arr = np.array([ "1","2","3","4","5"])
arr = arr.astype(np.int64)
arr

array([1, 2, 3, 4, 5])